# scrum4me-mcp — centralized HTTP server image (dist/http.js).
#
# The Prisma client is generated by the postinstall hook during `npm ci` in the
# deps stage, while prisma/schema.prisma is present. We carry the whole
# node_modules (including the generated client) into the runtime stage rather
# than re-running `prisma generate` there — with `npm ci --omit=dev` the prisma
# CLI is absent and the postinstall `|| true` would silently skip generation,
# leaving an unusable client. Driver-adapter mode (PrismaPg) needs no native
# engine binary, so a plain copy is portable across the alpine stages.
FROM node:22-alpine AS deps
WORKDIR /app
COPY package*.json ./
COPY prisma ./prisma
RUN npm ci

FROM node:22-alpine AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY package*.json tsconfig.json ./
COPY prisma ./prisma
COPY src ./src
RUN npm run build

FROM node:22-alpine AS runtime
RUN apk add --no-cache tini
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=8000
ENV HOST=0.0.0.0
# node_modules from deps already contains the generated Prisma client.
COPY --from=deps /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY package*.json ./
COPY prisma ./prisma
EXPOSE 8000
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["node", "dist/http.js"]
