import {beforeEach,afterEach,it,expect} from 'vitest'
import {mkdtemp,mkdir,writeFile,readFile,rm,realpath} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {pathToFileURL} from 'node:url'
import {execFileSync} from 'node:child_process'
import {randomUUID} from 'node:crypto'
import {createDispatchWorkspace,createCodeArtifact,verifyCodeArtifact} from '../../src/dispatch/workspace.js'
let root:string,origin:string,base:string,repoUrl:string
const git=(dir:string,...args:string[])=>execFileSync('git',args,{cwd:dir,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim()
beforeEach(async()=>{root=await realpath(await mkdtemp(join(tmpdir(),'ip08-workspace-')));origin=join(root,'origin');await mkdir(origin);git(origin,'init');git(origin,'config','user.name','Test');git(origin,'config','user.email','test@example.test');await writeFile(join(origin,'a.txt'),'old\n');git(origin,'add','.');git(origin,'commit','-m','old');base=git(origin,'rev-parse','HEAD');await writeFile(join(origin,'a.txt'),'latest\n');git(origin,'commit','-am','latest');repoUrl=pathToFileURL(origin).href})
afterEach(async()=>rm(root,{recursive:true,force:true}))
function service(){return createDispatchWorkspace({root:join(root,'workspaces'),loadRepository:async id=>id==='p'?repoUrl:null,allowedProtocols:['file']})}
const input=()=>({version:1 as const,product_id:'p',action:'free_task' as const,objective:'Fix',verification:'test',response_format:'md',requirements:{access:'repo_write' as const,environment_keys:[],repository:{product_id:'p',base_sha:base}},publish:'artifact' as const,reply_to:'mac:jp'})
it('prepares an isolated repository at the exact old base with the exact requested branch',async()=>{const requestId=randomUUID(),attemptId=randomUUID(),x=await service().prepareDispatchWorkspace({...input(),requestId},attemptId);expect(x.branch).toBe(`codex/queue-${requestId}`);expect(x.baseSha).toBe(base);expect(await readFile(join(x.path,'a.txt'),'utf8')).toBe('old\n');expect(git(x.path,'remote','get-url','origin')).toBe(repoUrl);expect(git(x.path,'rev-list','--count','HEAD')).toBe('1');expect(git(origin,'show','HEAD:a.txt')).toBe('latest');await expect(service().prepareDispatchWorkspace({...input(),requestId},attemptId)).rejects.toThrow()})
it('refuses moving refs, different Task repository and absolute attempt paths',async()=>{const requestId=randomUUID();await expect(service().prepareDispatchWorkspace({...input(),requirements:{...input().requirements,repository:{product_id:'p',base_sha:'main'}},requestId},randomUUID())).rejects.toThrow();await expect(service().prepareDispatchWorkspace({...input(),requestId,snapshot:{repository:{repo_url:'https://wrong/repo',base_sha:base}}},randomUUID())).rejects.toThrow();await expect(service().prepareDispatchWorkspace({...input(),requestId},'/tmp/escape')).rejects.toThrow()})
it('imports actual minimal bundle/diff into another repo and validates base/head/files/checks',async()=>{const requestId=randomUUID(),x=await service().prepareDispatchWorkspace({...input(),requestId},randomUUID());const baseBundle=await service().prepareRepositorySource(input(),randomUUID(),{});git(x.path,'config','user.name','Test');git(x.path,'config','user.email','test@example.test');await writeFile(join(x.path,'a.txt'),'fixed\n');git(x.path,'commit','-am','fix');const head=git(x.path,'rev-parse','HEAD'),checks=[{name:'test',status:'passed' as const,evidence:'exit 0'}];const bytes=await createCodeArtifact(x.path,{repoUrl,baseSha:base,headSha:head,branch:x.branch,checks});const result=await verifyCodeArtifact(bytes,baseBundle.bytes,{repoUrl,baseSha:base,headSha:head,branch:x.branch,checks});expect(result.files).toEqual(['a.txt']);const changed=JSON.parse(Buffer.from(bytes).toString());changed.files=[];await expect(verifyCodeArtifact(Buffer.from(JSON.stringify(changed)),baseBundle.bytes,{repoUrl,baseSha:base,headSha:head,branch:x.branch,checks})).rejects.toThrow();expect(Buffer.from(bytes).toString()).not.toContain(git(origin,'rev-parse','HEAD'))})
it('rejects agent-installed Git filters before using a mutable workspace as a code artifact source',async()=>{const requestId=randomUUID(),x=await service().prepareDispatchWorkspace({...input(),requestId},randomUUID());git(x.path,'config','filter.evil.clean','touch /tmp/never-run-dispatch-filter');await expect(createCodeArtifact(x.path,{repoUrl,baseSha:base,headSha:base,branch:x.branch,checks:[]})).rejects.toThrow('DISPATCH_FORBIDDEN')})
it('blocks executable filters, includes and Git filesystem escapes before a trusted collector reads them',async()=>{
 const x=await service().prepareDispatchWorkspace({...input(),requestId:randomUUID()},randomUUID());git(x.path,'config','user.name','Test');git(x.path,'config','user.email','test@example.test');await writeFile(join(x.path,'.gitattributes'),'*.txt filter=attack\n');git(x.path,'add','.gitattributes');git(x.path,'commit','-m','attributes');const expected={repoUrl,baseSha:base,headSha:git(x.path,'rev-parse','HEAD'),branch:x.branch,checks:[]},marker=join(root,'executed');git(x.path,'config','filter.attack.clean',`sh -c 'touch "${marker}"; cat'`);await writeFile(join(x.path,'a.txt'),'old\n');await expect(createCodeArtifact(x.path,expected)).rejects.toThrow('DISPATCH_FORBIDDEN');await expect(readFile(marker)).rejects.toThrow();git(x.path,'config','--remove-section','filter.attack');git(x.path,'config','include.path',join(root,'outside-config'));await expect(createCodeArtifact(x.path,expected)).rejects.toThrow('DISPATCH_FORBIDDEN');git(x.path,'config','--remove-section','include');await writeFile(join(x.path,'.git','objects','info','alternates'),join(root,'host-secrets'));await expect(createCodeArtifact(x.path,expected)).rejects.toThrow('DISPATCH_FORBIDDEN')
})
it('preserves a verified no-change base with an empty diff without exporting history',async()=>{const x=await service().prepareDispatchWorkspace({...input(),requestId:randomUUID()},randomUUID()),expected={repoUrl,baseSha:base,headSha:base,branch:x.branch,checks:[]},source=await service().prepareRepositorySource(input(),randomUUID(),{}),bytes=await createCodeArtifact(x.path,expected);expect(JSON.parse(Buffer.from(bytes).toString()).bundle).toBe('');expect(await verifyCodeArtifact(bytes,source.bytes,expected)).toEqual({files:[]})})
it('refuses host-directed core.worktree and symlinked Git objects before executing Git',async()=>{const x=await service().prepareDispatchWorkspace({...input(),requestId:randomUUID()},randomUUID()),expected={repoUrl,baseSha:base,headSha:base,branch:x.branch,checks:[]};git(x.path,'config','core.worktree',join(root,'forbidden-host-path'));await expect(createCodeArtifact(x.path,expected)).rejects.toThrow('DISPATCH_FORBIDDEN');git(x.path,'config','--unset','core.worktree');const fs=await import('node:fs/promises');await fs.symlink(join(root,'forbidden-host-objects'),join(x.path,'.git','objects','host-link'));await expect(createCodeArtifact(x.path,expected)).rejects.toThrow('DISPATCH_FORBIDDEN')})
it('does not run configured hooks or textconv commands during collection',async()=>{const x=await service().prepareDispatchWorkspace({...input(),requestId:randomUUID()},randomUUID()),expected={repoUrl,baseSha:base,headSha:base,branch:x.branch,checks:[]},marker=join(root,'hook-executed');await writeFile(join(x.path,'.git','hooks-malicious'),'#!/bin/sh\ntouch '+marker+'\n',{mode:0o755});git(x.path,'config','core.hooksPath',root);expect(await createCodeArtifact(x.path,expected)).toBeInstanceOf(Uint8Array);await expect(readFile(marker)).rejects.toThrow();git(x.path,'config','diff.attack.textconv','touch '+marker);await expect(createCodeArtifact(x.path,expected)).rejects.toThrow('DISPATCH_FORBIDDEN');await expect(readFile(marker)).rejects.toThrow()})
it('preserves raw NUL-separated UTF-8 paths and complete diff bytes across real export and import',async()=>{
 const x=await service().prepareDispatchWorkspace({...input(),requestId:randomUUID()},randomUUID()),names=[' leading.txt','tab\tname.txt','line\nbreak.txt','trailing.txt ','\ufeffbom-name.txt']
 git(x.path,'config','user.name','Test');git(x.path,'config','user.email','test@example.test')
 for(const name of names)await writeFile(join(x.path,name),'content with trailing spaces  \n\n')
 await writeFile(join(x.path,'binary.bin'),Buffer.from([0,255,1,2,10]))
 git(x.path,'add','.');git(x.path,'commit','-m','special filenames')
 const expected={repoUrl,baseSha:base,headSha:git(x.path,'rev-parse','HEAD'),branch:x.branch,checks:[]},source=await service().prepareRepositorySource(input(),randomUUID(),{}),bytes=await createCodeArtifact(x.path,expected),artifact=JSON.parse(Buffer.from(bytes).toString('utf8'))
 const raw=(...args:string[])=>execFileSync('git',args,{cwd:x.path,stdio:['ignore','pipe','pipe']})
 const actualFiles=raw('diff','--name-only','-z',base,expected.headSha).toString('utf8').split('\0').slice(0,-1)
 expect(actualFiles).toContain(' leading.txt');expect(artifact.files).toEqual(actualFiles)
 expect(Buffer.from(artifact.diff,'utf8')).toEqual(raw('diff','--binary','--no-ext-diff','--no-textconv',base,expected.headSha))
 expect((await verifyCodeArtifact(bytes,source.bytes,expected)).files).toEqual(actualFiles)
})
it('rejects invalid UTF-8 Git path bytes in a real imported bundle instead of replacement decoding',async()=>{
 const x=await service().prepareDispatchWorkspace({...input(),requestId:randomUUID()},randomUUID());git(x.path,'config','user.name','Test');git(x.path,'config','user.email','test@example.test')
 const blob=execFileSync('git',['hash-object','-w','--stdin'],{cwd:x.path,input:'content'}).toString().trim()
 const tree=execFileSync('git',['mktree','-z'],{cwd:x.path,input:Buffer.concat([Buffer.from(`100644 blob ${blob}\tbad-`),Buffer.from([255]),Buffer.from('.txt\0')])}).toString().trim()
 const head=execFileSync('git',['commit-tree',tree,'-p',base],{cwd:x.path,input:'invalid path\n'}).toString().trim();git(x.path,'update-ref',`refs/heads/${x.branch}`,head)
 const bundlePath=join(root,'invalid-path.bundle');git(x.path,'bundle','create',bundlePath,`${base}..HEAD`)
 const expected={repoUrl,baseSha:base,headSha:head,branch:x.branch,checks:[]},source=await service().prepareRepositorySource(input(),randomUUID(),{})
 const bytes=Buffer.from(JSON.stringify({version:1,...expected,files:git(x.path,'diff','--name-only','-z',base,head).split('\0').filter(Boolean),diff:git(x.path,'diff','--binary','--no-ext-diff','--no-textconv',base,head),bundle:(await readFile(bundlePath)).toString('base64')}))
 await expect(verifyCodeArtifact(bytes,source.bytes,expected)).rejects.toThrow('DISPATCH_UNSUPPORTED_ENCODING')
})
it('rejects non-UTF8 textual diff bytes and retains the committed workspace',async()=>{
 const x=await service().prepareDispatchWorkspace({...input(),requestId:randomUUID()},randomUUID());git(x.path,'config','user.name','Test');git(x.path,'config','user.email','test@example.test');await writeFile(join(x.path,'a.txt'),Buffer.from([255,10]));git(x.path,'commit','-am','non UTF8 text')
 const expected={repoUrl,baseSha:base,headSha:git(x.path,'rev-parse','HEAD'),branch:x.branch,checks:[]}
 await expect(createCodeArtifact(x.path,expected)).rejects.toThrow('DISPATCH_UNSUPPORTED_ENCODING')
 expect(git(x.path,'rev-parse','HEAD')).toBe(expected.headSha);expect(await readFile(join(x.path,'a.txt'))).toEqual(Buffer.from([255,10]))
})
