import { describe, it, expect } from 'vitest'
import { createHash } from 'node:crypto'

import {
  collectReleaseMetadata,
  RELEASE_NODE_VERSION,
  RELEASE_REPOSITORY,
  RELEASE_SOURCE_REF,
  type ReleaseMetadataDependencies,
} from '../scripts/release-metadata.js'

const sha256 = (buf: Buffer): string =>
  createHash('sha256').update(buf).digest('hex')

const DEFAULT_HEAD = 'a'.repeat(40)
const DEFAULT_PARENTS: readonly [string, string] = ['b'.repeat(40), 'c'.repeat(40)]
const DEFAULT_SUBMODULE_SHA = 'd'.repeat(40)

const DEFAULT_LOCK = Buffer.from('{"lockfileVersion":3,"name":"scrum4me-mcp"}\n')
const DEFAULT_SCHEMA = Buffer.from('// generated by gen-schema.sh\nmodel Task {}\n')
const DEFAULT_SURFACE = Buffer.from('{"tools":[{"name":"health"}]}\n')

interface FakeOverrides {
  head?: string
  originMain?: string
  parents?: readonly string[]
  nodeVersion?: string
  submoduleStatus?: string
  schemaStatus?: string
  packageLock?: Buffer
  schemaFile?: Buffer
  toolSurface?: Buffer
  evidence?: Map<string, string>
}

/**
 * Build a fully-valid dependency double that returns coherent build metadata,
 * then let individual specs override exactly the one fact under test. The gate
 * evidence is derived from the file bytes so the default is internally
 * consistent: schema↔generated schema, typecheck↔package-lock, canary↔surface.
 */
function fakeReleaseMetadataDeps(
  overrides: FakeOverrides = {},
): ReleaseMetadataDependencies {
  const head = overrides.head ?? DEFAULT_HEAD
  const originMain = overrides.originMain ?? head
  const parents = overrides.parents ?? DEFAULT_PARENTS
  const nodeVersion = overrides.nodeVersion ?? `v${RELEASE_NODE_VERSION}`
  const submoduleStatus =
    overrides.submoduleStatus ??
    ` ${DEFAULT_SUBMODULE_SHA} vendor/scrum4me-shared (v0.2.0)\n`
  const schemaStatus = overrides.schemaStatus ?? ''
  const packageLock = overrides.packageLock ?? DEFAULT_LOCK
  const schemaFile = overrides.schemaFile ?? DEFAULT_SCHEMA
  const toolSurface = overrides.toolSurface ?? DEFAULT_SURFACE
  const evidence =
    overrides.evidence ??
    new Map<string, string>([
      ['schema', sha256(schemaFile)],
      ['typecheck', sha256(packageLock)],
      ['tests', 'e'.repeat(64)],
      ['stdio_canary', sha256(toolSurface)],
    ])

  return {
    git: async (args) => {
      const key = args.join(' ')
      if (key === 'rev-parse HEAD') return `${head}\n`
      if (key === `rev-parse ${RELEASE_SOURCE_REF}`) return `${originMain}\n`
      if (key === 'show -s --format=%P HEAD') return `${parents.join(' ')}\n`
      if (key === 'submodule status --recursive') return submoduleStatus
      if (key === 'status --porcelain -- prisma/schema.prisma') return schemaStatus
      throw new Error(`unexpected git invocation: ${key}`)
    },
    readFile: async (path) => {
      if (path === 'package-lock.json') return packageLock
      if (path === 'prisma/schema.prisma') return schemaFile
      if (path === '.release/tool-surface.json') return toolSurface
      throw new Error(`unexpected readFile: ${path}`)
    },
    nodeVersion: () => nodeVersion,
    gateEvidence: async () => evidence,
  }
}

describe('collectReleaseMetadata — happy path', () => {
  it('attests the exact origin/main merge commit with coherent digests', async () => {
    const metadata = await collectReleaseMetadata(fakeReleaseMetadataDeps())

    expect(metadata.version).toBe('scrum4me-mcp-build/v1')
    expect(metadata.repository).toBe(RELEASE_REPOSITORY)
    expect(metadata.source_ref).toBe(RELEASE_SOURCE_REF)
    expect(metadata.commit).toBe(DEFAULT_HEAD)
    expect(metadata.attested_merge_parents).toEqual(DEFAULT_PARENTS)
    expect(metadata.submodules).toEqual({
      'vendor/scrum4me-shared': DEFAULT_SUBMODULE_SHA,
    })
    expect(metadata.node_version).toBe(RELEASE_NODE_VERSION)
    expect(metadata.package_lock_sha256).toBe(sha256(DEFAULT_LOCK))
    expect(metadata.generated_schema_sha256).toBe(sha256(DEFAULT_SCHEMA))
    expect(metadata.tool_surface_sha256).toBe(sha256(DEFAULT_SURFACE))
    expect(metadata.gates.map((g) => g.id)).toEqual([
      'schema',
      'typecheck',
      'tests',
      'stdio_canary',
    ])
    expect(metadata.gates.every((g) => g.result === 'passed')).toBe(true)
  })
})

describe('collectReleaseMetadata — merge ancestry & remote ref', () => {
  it('rejects a candidate that is not the exact origin/main merge commit', async () => {
    const deps = fakeReleaseMetadataDeps({
      head: 'a'.repeat(40),
      originMain: 'b'.repeat(40),
      parents: ['c'.repeat(40)],
    })

    await expect(collectReleaseMetadata(deps)).rejects.toThrow(
      'RELEASE_COMMIT_NOT_ORIGIN_MAIN_MERGE',
    )
  })

  it('rejects when origin/main has moved off the built HEAD', async () => {
    const deps = fakeReleaseMetadataDeps({
      head: 'a'.repeat(40),
      originMain: 'f'.repeat(40),
      parents: ['b'.repeat(40), 'c'.repeat(40)],
    })

    await expect(collectReleaseMetadata(deps)).rejects.toThrow(
      'RELEASE_COMMIT_NOT_ORIGIN_MAIN_MERGE',
    )
  })

  it('rejects a single-parent (non-merge) HEAD even when it equals origin/main', async () => {
    const deps = fakeReleaseMetadataDeps({ parents: [DEFAULT_HEAD] })

    await expect(collectReleaseMetadata(deps)).rejects.toThrow(
      'RELEASE_COMMIT_NOT_ORIGIN_MAIN_MERGE',
    )
  })
})

describe('collectReleaseMetadata — pinned toolchain', () => {
  it('rejects a Node version other than the pinned release toolchain', async () => {
    const deps = fakeReleaseMetadataDeps({ nodeVersion: 'v22.23.2' })

    await expect(collectReleaseMetadata(deps)).rejects.toThrow(
      'NODE_VERSION_MISMATCH',
    )
  })
})

describe('collectReleaseMetadata — submodules', () => {
  it('rejects an uninitialised submodule', async () => {
    const deps = fakeReleaseMetadataDeps({
      submoduleStatus: `-${DEFAULT_SUBMODULE_SHA} vendor/scrum4me-shared\n`,
    })

    await expect(collectReleaseMetadata(deps)).rejects.toThrow(
      'SUBMODULE_NOT_CLEAN',
    )
  })

  it('rejects a dirty submodule whose checkout differs from the index', async () => {
    const deps = fakeReleaseMetadataDeps({
      submoduleStatus: `+${DEFAULT_SUBMODULE_SHA} vendor/scrum4me-shared (v0.2.0-1-gabc)\n`,
    })

    await expect(collectReleaseMetadata(deps)).rejects.toThrow(
      'SUBMODULE_NOT_CLEAN',
    )
  })
})

describe('collectReleaseMetadata — committed generated schema', () => {
  it('rejects an uncommitted generated Prisma schema', async () => {
    const deps = fakeReleaseMetadataDeps({
      schemaStatus: ' M prisma/schema.prisma\n',
    })

    await expect(collectReleaseMetadata(deps)).rejects.toThrow(
      'GENERATED_SCHEMA_NOT_COMMITTED',
    )
  })
})

describe('collectReleaseMetadata — gate evidence', () => {
  it('rejects an absent required gate', async () => {
    const evidence = new Map<string, string>([
      ['schema', sha256(DEFAULT_SCHEMA)],
      ['typecheck', sha256(DEFAULT_LOCK)],
      ['stdio_canary', sha256(DEFAULT_SURFACE)],
    ])
    const deps = fakeReleaseMetadataDeps({ evidence })

    await expect(collectReleaseMetadata(deps)).rejects.toThrow(
      'GATE_EVIDENCE_MISSING',
    )
  })

  it('rejects an unknown gate key', async () => {
    const evidence = new Map<string, string>([
      ['schema', sha256(DEFAULT_SCHEMA)],
      ['typecheck', sha256(DEFAULT_LOCK)],
      ['tests', 'e'.repeat(64)],
      ['stdio_canary', sha256(DEFAULT_SURFACE)],
      ['deploy', 'f'.repeat(64)],
    ])
    const deps = fakeReleaseMetadataDeps({ evidence })

    await expect(collectReleaseMetadata(deps)).rejects.toThrow(
      'GATE_EVIDENCE_UNKNOWN_KEY',
    )
  })

  it('rejects a malformed (non-sha256) gate digest', async () => {
    const evidence = new Map<string, string>([
      ['schema', sha256(DEFAULT_SCHEMA)],
      ['typecheck', sha256(DEFAULT_LOCK)],
      ['tests', 'not-a-sha'],
      ['stdio_canary', sha256(DEFAULT_SURFACE)],
    ])
    const deps = fakeReleaseMetadataDeps({ evidence })

    await expect(collectReleaseMetadata(deps)).rejects.toThrow(
      'GATE_EVIDENCE_MALFORMED',
    )
  })
})

describe('collectReleaseMetadata — content-hash bindings', () => {
  it('rejects when the package-lock digest is not bound by the typecheck gate', async () => {
    const evidence = new Map<string, string>([
      ['schema', sha256(DEFAULT_SCHEMA)],
      ['typecheck', '0'.repeat(64)],
      ['tests', 'e'.repeat(64)],
      ['stdio_canary', sha256(DEFAULT_SURFACE)],
    ])
    const deps = fakeReleaseMetadataDeps({ evidence })

    await expect(collectReleaseMetadata(deps)).rejects.toThrow(
      'LOCK_HASH_MISMATCH',
    )
  })

  it('rejects when the generated-schema digest is not bound by the schema gate', async () => {
    const evidence = new Map<string, string>([
      ['schema', '0'.repeat(64)],
      ['typecheck', sha256(DEFAULT_LOCK)],
      ['tests', 'e'.repeat(64)],
      ['stdio_canary', sha256(DEFAULT_SURFACE)],
    ])
    const deps = fakeReleaseMetadataDeps({ evidence })

    await expect(collectReleaseMetadata(deps)).rejects.toThrow(
      'SCHEMA_HASH_MISMATCH',
    )
  })

  it('rejects when the tool-surface digest is not bound by the stdio_canary gate', async () => {
    const evidence = new Map<string, string>([
      ['schema', sha256(DEFAULT_SCHEMA)],
      ['typecheck', sha256(DEFAULT_LOCK)],
      ['tests', 'e'.repeat(64)],
      ['stdio_canary', '0'.repeat(64)],
    ])
    const deps = fakeReleaseMetadataDeps({ evidence })

    await expect(collectReleaseMetadata(deps)).rejects.toThrow(
      'TOOL_SURFACE_HASH_MISMATCH',
    )
  })
})
